CREATE TYPE "chat_types" AS ENUM (
    'PERSONAL',
    'GROUP'
    );

CREATE TYPE "content_types" AS ENUM (
    'IMAGE',
    'FILE',
    'VIDEO',
    'AUDIO'
    );

CREATE TYPE "group_chat_member_authority" AS ENUM (
    'USER',
    'ADMIN'
    );

CREATE TABLE "users" (
    id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE "refresh_tokens" (
    id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    token TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    expired_at TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE chats
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type CHAT_TYPES NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE contents
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name    TEXT                            NOT NULL,
    file_path    TEXT                            NOT NULL,
    size         BIGINT                                  NOT NULL,
    uploaded_at  TIMESTAMP             NOT NULL,
    content_type CONTENT_TYPES NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE group_chats
(
    chat_id       BIGINT       NOT NULL,
    owner_id      BIGINT       NOT NULL,
    title         TEXT NOT NULL,
    members_count INTEGER      NOT NULL,
    PRIMARY KEY (chat_id)
);

CREATE TABLE group_chats_members
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id   BIGINT                                  NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    authority group_chat_member_authority             NOT NULL DEFAULT 'USER',
    PRIMARY KEY (id)
);

CREATE TABLE message_contents
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id BIGINT                                 NOT NULL,
    content_id BIGINT                                  NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE messages
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id   BIGINT                                   NOT NULL,
    sender_id BIGINT                                   NOT NULL,
    send_at   TIMESTAMP              NOT NULL,
    text      VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

CREATE TABLE personal_chats
(
    chat_id    BIGINT NOT NULL,
    member1_id BIGINT,
    member2_id BIGINT,
    CONSTRAINT pk_personal_chats PRIMARY KEY (chat_id)
);


ALTER TABLE "refresh_tokens"
    ADD FOREIGN KEY(user_id) REFERENCES users(id);

ALTER TABLE group_chats
    ADD FOREIGN KEY (chat_id) REFERENCES chats (id);

ALTER TABLE messages
    ADD FOREIGN KEY (chat_id) REFERENCES chats (id);

ALTER TABLE message_contents
    ADD FOREIGN KEY (content_id) REFERENCES contents (id);

ALTER TABLE message_contents
    ADD FOREIGN KEY (message_id) REFERENCES messages (id);

ALTER TABLE personal_chats
    ADD FOREIGN KEY (chat_id) REFERENCES chats (id);