server:
  port: 8082

spring:
  application:
    name:  ChatService

  datasource:
    url: jdbc:postgresql://localhost:5432/messenger
    username: messenger-user
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: false
    baseline-on-migrate: true

