server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        # === ROUTE 1: UserService ===
        - id: user-service
          uri: http://user-service:8080 # внутри контейнера слушаем единый порт
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2

        # === ROUTE 2: ChatService HTTP endpoints ===
        - id: chat-service
          uri: http://chat-service:8080
          predicates:
            - Path=/api/chat/**
          filters:
            - StripPrefix=2

        # === ROUTE 3: ChatService WebSocket ===
        - id: chat-ws
          uri: http://chat-service:8080
          predicates:
            - Path=/ws-chat/**
          filters:
            - name: RemoveRequestHeader
              args:
                name: Sec-WebSocket-Key

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    reactor.netty.http.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"